export const datasetVersion='AEC-DEMO-2026.1';
export const modules=[
 {id:'tender-contracts',name:'Tendering & Contracts',short:'Tender & contract review',prefix:'TC',grain:'One tender package and its contract outcome',record:'tender package',owner:'Contracts manager',
  reference:'Contract Management.txt, pp. 1–4; Procurement.txt, Purchase Enquiry',
  referenceLines:'36009–36165; 141191–141230',
  types:['Open tender','Selective tender','Negotiated contract','Framework call-off'],
  statuses:['Draft','In evaluation','Awarded','Lost','Cancelled','Contract active','Contract closed'],
  asis:'Tender registers in spreadsheets, scope revisions over email, and paper bid approvals make it difficult to prove which BOQ was evaluated.',
  steps:['Package and BOQ','Enquiry','Bid normalization','Technical review','Commercial recommendation','Award approval','Contract and variations'],
  requirements:[['Revision control','boq_revision, tender_id','Freeze the evaluated BOQ revision; a later revision triggers renewed review.','Revise a package after evaluation and verify the award is blocked until reviewed.'],['Bid normalization','bid_count, bid_amount, technical_score','Compare bids in one currency and scope; record exclusions explicitly.','A low-price noncompliant bid must remain ineligible.'],['Award authority','approval_level, approved_amount','Commercial approval and technical acceptance must both precede award.','An unapproved recommendation cannot create an active contract.'],['Contract terms','retention_pct, payment_days, contract_id','Carry approved payment terms and retention into the signed contract.','Verify terms survive the tender-to-contract handoff.'],['Variation register','variation_amount, variation_status','Unapproved variations remain separate from the approved contract value.','Pending variation must not inflate the approved commitment.']],
  deliverables:['BOQ revision matrix and tender workflow','Bid normalization and authority rules','Contract/variation traceability and UAT evidence'],
  metric:'Package value',amountField:'package_value',target:'award_delay',targetLabel:'Award delayed beyond planned evaluation days',features:['bid_count','scope_changes','approval_levels','planned_days'],featureLabels:['Bids received','Scope changes at review','Approval levels','Planned evaluation days'],
  integration:'Approved contract IDs feed orders and receivable records; variation values remain versioned.',risk:'Late scope revisions invalidate a commercial comparison.',migration:'Tender packages, BOQ revisions, open bids, signed terms and approved variations',app:'Award Risk Reviewer'},
 {id:'procurement-subcontracting',name:'Procurement & Subcontracting',short:'Procurement control tower',prefix:'PS',grain:'One purchase order or subcontract work order',record:'order',owner:'Procurement manager',
  reference:'Procurement.txt, pp. 1–2; Subcontracting.txt, pp. 1–2',referenceLines:'141136–141230; 176235–176320',
  types:['Material PO','Plant hire PO','Service PO','Call-off PO','Labour work order','Measured-work subcontract'],statuses:['Draft','Pending approval','Rejected','Approved','Part delivered','Completed','Cancelled'],
  asis:'Site engineers send requirements through WhatsApp and paper requisitions. Buyers compare quotes in separate spreadsheets; signed work orders and valuation sheets are hard to reconcile.',
  steps:['Requisition','RFQ and comparison','Budget check','Approval','PO / work order','GRN / valuation','Invoice matching'],
  requirements:[['Order types','order_type, requisition_id','Separate materials, plant hire, services, call-offs, labour and measured-work orders.','A labour work order requires a trade and valuation basis rather than a stock item.'],['Approval workflow','approval_level, order_amount','Demo authority: buyer prepares; project manager reviews; commercial manager approves up to INR 500,000; director above that. No self-approval.','Test values of 499,999, 500,000 and 500,001 and verify routing.'],['Budget availability','budget_available, order_amount','Commit only approved orders within the available budget or with an authorized override.','An over-budget draft cannot be released without the override record.'],['Receipt and certification','accepted_qty, certified_amount','Material receipts and subcontract valuations use separate acceptance evidence.','A rejected receipt cannot be included in a payable invoice.'],['Retention and advance','retention_pct, advance_pct','Record contract-specific retention and advance recovery without double counting.','Verify a partial certificate retains and recovers the correct amounts.']],
  deliverables:['AS-IS/TO-BE requisition and approval maps','Order-type and authority configuration','GRN, valuation and invoice-match acceptance pack'],metric:'Order value',amountField:'order_amount',target:'late_delivery',targetLabel:'Completion after the promised date',features:['lead_days','prior_delay_rate','approval_levels','urgency'],featureLabels:['Promised lead days','Prior supplier delay rate','Approval levels','Urgency (1–3)'],integration:'Order IDs connect to inventory receipts and AP invoices; work orders connect to valuations.',risk:'Poor supplier/item masters or open-order migration can duplicate commitments.',migration:'Approved suppliers, items, trades, open POs, work orders, accepted receipts and prior certificates',app:'Delivery Risk & Order Review'},
 {id:'inventory-warehouse',name:'Inventory & Warehouse Management',short:'Stock and warehouse review',prefix:'IW',grain:'One dated stock movement in an item/store ledger',record:'stock movement',owner:'Warehouse manager',
  reference:'Inventory.txt, pp. 1–2; Warehouse Management.txt, configuration and lot expiry',referenceLines:'85540–85610; 223179–223230',
  types:['Receipt','Issue','Return','Adjustment in','Adjustment out'],statuses:['Posted','Quarantined','Pending count','Count verified'],asis:'Paper GRNs, handwritten bin cards and spreadsheet issue registers leave stock balances and lot locations out of date.',
  steps:['Receive','Inspect','Accept / quarantine','Put away','Issue / return','Cycle count','Reconcile'],
  requirements:[['Item and UOM','item_id, uom','Maintain one stock unit per item and explicit purchase conversion.','A receipt in bags must convert to the approved stock unit.'],['Chronology','record_date, store_id, item_id','Post each item/store ledger in date order; reject a backdated movement before the last transaction.','Backdate a new issue and confirm it cannot change prior weighted averages.'],['Location control','warehouse_id, locator, lot_id','Track stock location and lot separately from the resource master.','Find a lot by locator and reconcile its quantity.'],['Stock availability','opening_qty, movement_qty, closing_qty','Issues cannot make available stock negative. Quarantined quantities are unavailable.','An issue above available quantity is blocked.'],['Stock correction','movement_type, approval_status','Quantity/value corrections require approval and a cycle-count reference.','A pending correction cannot alter a posted balance.']],deliverables:['Stock ledger and locator model','Receipt-to-issue controls','Cycle-count and correction UAT'],metric:'Movement value (absolute)',amountField:'movement_value',target:'stock_exception',targetLabel:'Cycle-count discrepancy discovered after posting',features:['days_since_count','movement_qty','manual_entry','item_value'],featureLabels:['Days since count','Movement quantity','Manual entry (0/1)','Unit value'],integration:'Receipts reference purchase orders; store/item balances reconcile by movement, not by summing snapshots.',risk:'Incorrect opening quantities or units distort every later valuation.',migration:'Item/store openings, accepted GRNs, lot locators and unit conversions',app:'Stock Exception Reviewer'},
 {id:'real-estate-sales',name:'Real Estate Sales',short:'Sales and collection review',prefix:'RS',grain:'One unique unit sales enquiry / booking opportunity',record:'sales opportunity',owner:'Sales operations manager',reference:'Property sales.txt, process configuration and sales workflow',referenceLines:'159241–159340',types:['Apartment','Villa','Retail','Office'],statuses:['Enquiry','Reserved','Booked','Agreement signed','Handed over','Cancelled'],asis:'Sales teams track enquiries in spreadsheets and reservation messages. Payment schedules and discount approvals are reconciled manually with finance.',steps:['Enquiry','Availability','Reservation','Discount approval','Booking','Agreement','Installments','Handover'],requirements:[['Unit availability','unit_id, booking_status','One active booking per unit; cancellation must explicitly release the unit.','Attempt two active bookings for one unit and verify the second is blocked.'],['Price and discount','list_price, discount_pct','Store approved discount separately from the list price.','An excessive discount must route to the sales head.'],['Payment schedule','booking_id, installment_no','Schedule amounts must add to the contracted consideration.','Round installment amounts and reconcile the final residual.'],['Collection allocation','collected_amount, scheduled_amount','Allocate receipts to identified installments; keep unapplied cash separate.','Partial collections cannot mark the full installment settled.'],['Cancellation','booking_status, refund_amount','A cancellation requires a reason and reviewed refund calculation.','Cancel a partly paid booking and verify receivable reversal/release.']],deliverables:['Lead-to-booking process and unit controls','Discount and installment rules','Sales-to-AR handoff tests'],metric:'Agreed consideration',amountField:'agreed_price',target:'booking_loss',targetLabel:'Opportunity lost or cancelled within 60 days',features:['response_days','discount_pct','prior_contact_count','financing_required'],featureLabels:['Response time (days)','Requested discount rate','Prior contacts','Financing required (0/1)'],integration:'Booked unit schedules can reference AR installments; customer IDs are fictional.',risk:'Duplicate unit reservations and incomplete installment migration.',migration:'Units, price lists, reservations, signed bookings and collection allocations',app:'Sales Follow-up Reviewer'},
 {id:'construction-assets',name:'Construction Assets — Fixed & Movable',short:'Asset reliability review',prefix:'CA',grain:'One asset-month snapshot for 500 assets across 10 months',record:'asset-month',owner:'Plant and asset manager',reference:'Fixed Assets.txt, pp. 1–2; PLant.txt, process overview',referenceLines:'64060–64130; 131520–131620',types:['Fixed','Movable'],statuses:['Available','Deployed','Under maintenance','Retired'],asis:'Asset registers, paper logbooks and informal site transfers make location, operating hours and maintenance responsibility difficult to verify.',steps:['Acquire','Capitalize','Assign custodian','Deploy','Log use','Maintain','Depreciate','Retire'],requirements:[['Asset register','asset_id, asset_type, acquisition_cost','Separate fixed assets from movable plant while retaining one unique ID.','Reject duplicate serial/asset registrations.'],['Custody and transfer','project_id, custodian_id','Transfers require receiving-site acceptance and effective dates.','Verify no overlapping active location for one asset.'],['Maintenance','maintenance_due_hours, operating_hours','Prevent deployment of unavailable equipment and track planned servicing.','A maintenance status blocks a new deployment.'],['Depreciation','useful_life_months, residual_value','Use an explicit demonstration straight-line policy; preserve book/period.','Never depreciate below the residual value.'],['Retirement','status, retirement_date','Retired assets cannot accrue new utilization.','Subsequent retired snapshots must show zero available/operating hours.']],deliverables:['Asset lifecycle and custody controls','Maintenance and depreciation design','Transfer and retirement UAT'],metric:'Monthly depreciation',amountField:'depreciation',target:'breakdown_next_month',targetLabel:'Unplanned breakdown in the following month',features:['age_months','utilization_rate','days_since_service','prior_breakdowns'],featureLabels:['Age (months)','Utilization rate','Days since service','Prior breakdowns'],integration:'Plant operator IDs share the HR master; asset cost is a snapshot, depreciation is a monthly flow.',risk:'Opening book values and missing maintenance histories undermine reconciliation.',migration:'Asset register, opening book values, custodians, meter readings and service dates',app:'Asset Maintenance Reviewer'},
 {id:'receivables-payables',name:'Accounts Receivable & Accounts Payable',short:'Invoice and settlement review',prefix:'FA',grain:'One AR or AP invoice with settlement allocations',record:'invoice',owner:'Finance controller',reference:'Accounts Payable.txt, pp. 1–4; Accounts Receivable.txt, pp. 1–2',referenceLines:'2–250; 15816–15890',types:['AR','AP'],statuses:['Draft','Disputed','Posted','Part settled','Settled','Overdue'],asis:'Invoices arrive by email; matching and approvals use spreadsheets. Separate receipt/payment trackers obscure unpaid balances.',steps:['Invoice','Match / certify','Approve','Post','Allocate settlement','Age balance','Reconcile'],requirements:[['Invoice identity','invoice_no, entity_id, invoice_type','Detect supplier/customer invoice duplicates using entity plus invoice number.','A duplicate document must be rejected before posting.'],['Source matching','source_id, match_variance','AP matches accepted order/receipt or certified work; standalone invoices have their own authority.','A price/quantity mismatch remains on hold.'],['Accounting period','record_date, ledger_period','Post only to an open demonstration period with defined control accounts.','Closed-period posting is blocked.'],['Settlement allocation','gross_amount, settled_amount, outstanding','Do not allocate more than the invoice balance; keep AR/AP totals separate.','Test partial settlement and over-allocation.'],['Aging','due_date, as_of_date','Age outstanding balances using the fixed reporting date.','Verify not-due, due-today and 1/30/60/90-day boundaries.']],deliverables:['Invoice/matching and settlement requirements','AR/AP control-account reconciliation','Period and aging acceptance tests'],metric:'Gross invoice value (AR + AP)',amountField:'gross_amount',target:'late_settlement',targetLabel:'Settlement later than contractual payment terms',features:['payment_days','prior_late_rate','match_variance','approval_levels'],featureLabels:['Payment terms (days)','Prior entity late-payment rate','Match variance rate','Approval levels'],integration:'Sample AP invoices link to completed orders; AR invoices link to contracts or sales. The ledger is a sample, not full source-system totals.',risk:'Migrating gross and open balances together can duplicate liabilities.',migration:'Customers/suppliers, invoice balances, allocation history and control-account mappings',app:'Invoice Priority Reviewer'},
 {id:'construction-hr',name:'Construction HR',short:'Workforce data quality review',prefix:'HR',grain:'One employee-month attendance summary for 500 employees across 10 months',record:'attendance summary',owner:'HR operations lead',reference:'Payroll.txt, Employment / Absence / Attendance; Timesheet & Payroll.txt, setup',referenceLines:'109361–109435; 218098–218155',types:['Site labour','Plant operator','Site engineer','Office staff'],statuses:['Draft','Submitted','Approved','Returned'],asis:'Site attendance is consolidated from paper muster rolls, shift messages and emailed leave records before HR approval.',steps:['Employee master','Deployment','Shift allocation','Attendance','Leave','Timesheet review','Approved payroll handoff'],requirements:[['Employee identity','employee_id, payroll_group','Use fictional IDs and one active employment record; do not store personal bank or government identifiers in the demo.','Reject duplicate employee-month attendance.'],['Shift and leave','scheduled_days, worked_days, paid_leave_days','Worked, leave and absence days must reconcile to scheduled days.','Overlapping leave and worked days are rejected.'],['Timesheet ownership','project_id, approver','Supervisor checks the site record; HR verifies exceptions.','The preparer cannot approve their own timesheet.'],['Overtime authorization','overtime_hours, overtime_approved','Payable overtime must be authorized before payroll cut-off.','Unapproved overtime stays out of payroll gross.'],['Handoff lock','attendance_id, status','Only approved attendance feeds payroll; other records remain held.','A returned timesheet cannot produce a paid payroll record.']],deliverables:['Employee-to-payroll data dictionary','Shift, absence and approval workflow','Attendance reconciliation and handoff UAT'],metric:'Worked days',amountField:'worked_days',target:'attendance_correction',targetLabel:'Attendance record needs clerical correction at review',features:['manual_entry','missing_punches','overtime_hours','shift_changes'],featureLabels:['Manual entry (0/1)','Missing punches','Overtime hours','Shift changes'],integration:'Employee and attendance IDs join Payroll directly; review scores concern data quality, not worker performance.',risk:'Duplicate employees and unapproved attendance corrupt payroll inputs.',migration:'Fictional employee master, payroll groups, calendars and approved attendance',app:'Attendance Quality Reviewer'},
 {id:'construction-payroll',name:'Construction Payroll',short:'Payroll reconciliation review',prefix:'PY',grain:'One employee-month pay record linked 1:1 to HR attendance',record:'pay record',owner:'Payroll lead',reference:'Payroll.txt, payroll elements; Timesheet & Payroll.txt, payroll groups and accounting',referenceLines:'109361–109435; 218098–218155',types:['Monthly staff','Monthly site'],statuses:['Held for attendance','Calculated','Under review','Approved','Paid'],asis:'Payroll teams rekey approved timesheets into salary spreadsheets, then reconcile allowances, deductions and project postings manually.',steps:['Approved attendance','Pay elements','Gross calculation','Deductions','Reconciliation','Payroll approval','Payment and posting'],requirements:[['Attendance eligibility','attendance_id, attendance_status','Hold payroll when the linked attendance is not approved.','A returned timesheet creates a held, unpaid payroll line.'],['Pay calculation','basic_pay, overtime_pay, allowance','Calculate gross from explicit approved components; use configured rates.','Verify paid leave, unpaid absence and authorized overtime.'],['Deductions','deductions, gross_pay','Demo deductions are configurable assumptions, not statutory advice. Net pay cannot be negative.','High deductions are capped or referred for review.'],['Reconciliation','net_pay, paid_amount, project_id','Reconcile gross less deductions to net and payment allocations to paid records.','An unpaid approved run must not count as cash disbursed.'],['Approval segregation','payroll_group, approver','Payroll preparer, reviewer and payment authority are separate roles.','A maker cannot release their own payroll batch.']],deliverables:['Salary elements and attendance mapping','Payroll reconciliation and release controls','Parallel-run and payment UAT'],metric:'Calculated net pay',amountField:'net_pay',target:'payroll_adjustment',targetLabel:'A payroll line needs correction before release',features:['overtime_hours','allowance','manual_adjustments','input_exceptions'],featureLabels:['Approved overtime hours','Allowance (INR)','Manual adjustments','Input exceptions'],integration:'The same HR attendance rows drive pay. HR changes require regeneration, recalculation and a new dataset version.',risk:'Cut-off changes after sign-off can invalidate the payroll parallel run.',migration:'Salary structures, approved attendance, open deductions and opening balances',app:'Payroll Exception Reviewer'}
];
export const modulePath=m=>'/modules/'+m.id;
export const workbookPath=m=>'/data/modules/'+m.id+'.xlsx';
export const moduleAppPath=m=>'/ai-app/module-'+m.id;
export const implementationStages=[
 ['Discover',1,2,'Business analyst',10,9000,'Agree process boundary, current channels and signed requirements'],
 ['Configure',3,5,'Functional consultant',15,10000,'Configure types, masters, access and approval rules'],
 ['Migrate & integrate',6,8,'Data engineer',15,11000,'Reconcile opening records and validate source-ID joins'],
 ['UAT & train',9,10,'QA / trainer',10,8000,'Pass critical scenarios; train operational and finance owners'],
 ['Cutover & stabilize',11,12,'Implementation lead',10,12000,'Approve go/no-go, reconcile first cycle and transfer support']
];

export const githubRepository='https://github.com/AtulIwale/Portfolio';
export const moduleGithubPath=m=>githubRepository+'/tree/main/modules/'+m.id;
